version: '3.8'

services:
  pharmacyhub-frontend-local:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
        ENV_FILE: .env
    image: pharmacyhub-frontend:local
    container_name: pharmacyhub-frontend-local
    env_file: ../env/.env.local
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
    networks:
      - pharmacyhub-local-network
    restart: unless-stopped
    environment:
      - NODE_ENV=development

networks:
  pharmacyhub-local-network:
    name: pharmacyhub-local-network
    external: true
