version: '3.8'

services:
  crm-frontend-dev:
    image: syedus06/crm-frontend:dev
    container_name: crm-frontend-dev
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_KEYCLOAK_URL=${NEXT_PUBLIC_KEYCLOAK_URL}
      - NEXT_PUBLIC_CAL_URL=${NEXT_PUBLIC_CAL_URL}
      - NEXT_PUBLIC_CAL_CLIENT_ID=${NEXT_PUBLIC_CAL_CLIENT_ID}
      - CAL_CLIENT_SECRET=${CAL_CLIENT_SECRET}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ${CRM_BASE:-/home/ubuntu/CRM}/dev/frontend/logs:/app/logs
    networks:
      - dev-network
      - proxy-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  dev-network:
    name: crm-dev-network
    external: true
  proxy-network:
    name: proxy-network
    external: true
