version: '3.8'

services:
  pharmacyhub-frontend-qa:
    image: syedus06/pharmacyhub-frontend:qa
    container_name: pharmacyhub-frontend-qa
    env_file: ../.env
    environment:
      - NODE_ENV=qa
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT:-3010}:3000"
    volumes:
      - ${CRM_BASE:-/home/ubuntu/PharmacyHub}/qa/frontend/logs:/app/logs
    networks:
      - qa-network
      - proxy-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  qa-network:
    name: pharmacyhub-qa-network
    external: true
  proxy-network:
    name: proxy-network
    external: true
