version: '3.8'

services:
  crm-frontend-prod:
    image: syedus06/crm-frontend:prod
    container_name: crm-frontend-prod
    env_file: ../.env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_KEYCLOAK_URL=${NEXT_PUBLIC_KEYCLOAK_URL}
      - NEXT_PUBLIC_CAL_URL=${NEXT_PUBLIC_CAL_URL}
      - NEXT_PUBLIC_CAL_CLIENT_ID=${NEXT_PUBLIC_CAL_CLIENT_ID}
      - CAL_CLIENT_SECRET=${CAL_CLIENT_SECRET}
    ports:
      - "${FRONTEND_PORT:-3020}:3000"
    volumes:
      - ${CRM_BASE:-/home/ubuntu/CRM}/prod/frontend/logs:/app/logs
    networks:
      - prod-network
      - proxy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prod-network:
    name: crm-prod-network
    external: true
  proxy-network:
    name: proxy-network
    external: true
