version: '3.8'

services:
  pharmacyhub-frontend-dev:
    image: syedus06/pharmacyhub-frontend:dev
    container_name: pharmacyhub-frontend-dev
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ${CRM_BASE:-/home/ubuntu/PharmacyHub}/dev/frontend/logs:/app/logs
    networks:
      - dev-network
      - proxy-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  dev-network:
    name: pharmacyhub-dev-network
    external: true
  proxy-network:
    name: proxy-network
    external: true
